### ISSUE TITLE
Telepresence does not install

### ISSUE THREAD

**Issue by nikolay** [datawire/homebrew-blackbird#1]
I have virtualenv installed, but it still complains about it.

**Comment by ark3** [comment]
Sorry you're having trouble, and thanks for reporting it. However, I'm having trouble reproducing the issue. Can you please copy-paste your `brew install` command and its output?

**Comment by nikolay** [comment]
```
==> Installing telepresence from datawire/blackbird
==> Downloading https://github.com/datawire/telepresence/archive/0.65.tar.gz
==> Downloading from https://codeload.github.com/datawire/telepresence/tar.gz/0.
######################################################################## 100.0%
==> env PATH=/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/sql
Last 15 lines from /Users/redacted/Library/Logs/Homebrew/telepresence/01.env:
2017-09-15 15:27:54 -0700

env
PATH=/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/openssl/bin:/usr/local/opt/python3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
make
virtualenv/bin/sshuttle-telepresence

virtualenv --python=python3 virtualenv
/bin/bash: virtualenv: command not found
make: *** [virtualenv] Error 127
```

Well, now when I did `which virtualenv`, it seems that I've installed it via `pip3 install --user virtualenv`, but if you're Python 3 only, why not use `venv` via `python3 -m venv /path/to/new/virtual/environment`, instead?

**Comment by ark3** [comment]
Good question. I've been exploring removing the virtualenv dependency in https://github.com/datawire/telepresence/issues/276. Using `python3 -m venv` and then `python3 -m pip` works okay on macOS and on Mac Travis (which we use for CI), but fails in other contexts. It seems we will have to address this for Homebrew separately from our CI scripts. 

In the meantime, you can work around this issue by installing virtualenv at the Brew system level (i.e. `pip3 install virtualenv`).

**Comment by nikolay** [comment]
Thanks! It works now!
