### ISSUE TITLE
homebrew-core's sshfs is marked as deprecated

### ISSUE THREAD

**Issue by sters** [datawire/homebrew-blackbird#11]
I got this message from `brew doctor`.
```
$ brew doctor
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sshfs
```
And I try to `brew uninstall`
```
$ brew uninstall --ignore-dependencies sshfs
Uninstalling /usr/local/Cellar/sshfs/2.10_2... (6 files, 95KB)
```
But `brew doctor` and `brew missing` says telepresence has missing dependencies.
```
$ brew doctor
Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install sshfs

Run `brew missing` for more details.

$ brew missing
telepresence: sshfs

$ brew info telepresence
datawire/blackbird/telepresence: stable 0.108
Local dev environment attached to a remote Kubernetes cluster
https://telepresence.io
/usr/local/Cellar/telepresence/0.108 (4 files, 426.7KB) *
  Built from source on 2020-10-18 at 16:34:26
From: https://github.com/datawire/homebrew-blackbird/blob/HEAD/Formula/telepresence.rb
==> Dependencies
Required: python ✔, torsocks ✔, sshfs ✘
```

Then, I found this pull request: https://github.com/Homebrew/homebrew-core/pull/64491

so I think I need to do something with this tap as well, but I don't know what to do.
Do you have any ideas?

**Comment by jclosure** [comment]
FYI, the sshfs formula was set to disabled for MacOS, because of it's dependency on osxfuse.  https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sshfs.rb#L23.

**Comment by scottbessler** [comment]
For those looking for a workaround you can install sshfs from here:
brew install gromgit/fuse/sshfs-mac

**Comment by Moulick** [comment]
Hi @donnyyung  can we please switch the sshfs dependency to "gromgit/fuse/sshfs-mac" ? this is a tap maintained by gromgit, one of the prolific brew contributor ?

**Comment by Moulick** [comment]
I made a PR for the same https://github.com/datawire/homebrew-blackbird/pull/13
