### ISSUE TITLE
linux: telepresence formula quietly installs broken binary

### ISSUE THREAD

**Issue by nicks** [datawire/homebrew-blackbird#19]
the current formula unconditionally installs a darwin binary:
https://github.com/datawire/homebrew-blackbird/blob/90de1d1834dae3728b7af662136cd8066e047095/Formula/telepresence.rb#L6

But homebrew supports Linux now!
https://docs.brew.sh/Homebrew-on-Linux

If I try to install on Linux, I get a broken binary. :sob: 

Recommended fixes:
- Emit an error if a linux user tries to install the formula, OR
- Fix the formula to detect linux and use the linux binary.

(Homebrew has nice on_macos and on_linux directives that make this easy now, here's an example - https://github.com/tilt-dev/homebrew-tap/blob/master/tilt.rb#L10)

**Comment by lhriley** [comment]
Resolved by: https://github.com/telepresenceio/telepresence/pull/3282
