### ISSUE TITLE
kubernaut does not install

### ISSUE THREAD

**Issue by nikolay** [datawire/homebrew-blackbird#2]
It complains about a hash mismatch.

**Comment by ark3** [comment]
Sorry, this is not ready yet. Please use `pip` to install Kubernaut for now, as described in [the macOS install doc](https://github.com/datawire/kubernaut#macos): 

```shell
$ brew install python3
$ pip3 install kubernaut
```

**Comment by nikolay** [comment]
Okay, thanks!
