### ISSUE TITLE
Cannot install telepresence in macOS High Sierra v10.13.2

### ISSUE THREAD

**Issue by reinodenoia** [datawire/homebrew-blackbird#3]
brew install socat datawire/blackbird/telepresence

Warning: socat 1.7.3.2_1 is already installed
==> Installing telepresence from datawire/blackbird
==> Downloading https://github.com/datawire/telepresence/archive/0.73.tar.gz
Already downloaded: /Users/mariolinha/Library/Caches/Homebrew/telepresence-0.73.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
Already downloaded: /Users/mariolinha/Library/Caches/Homebrew/telepresence--homebrew-virtualenv-15.1.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/telepresence--homebrew-virtualenv-20180116-88682-1h0pj45/target --single-version-e
Last 15 lines from /Users/mariolinha/Library/Logs/Homebrew/telepresence/01.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/telepresence--homebrew-virtualenv-20180116-88682-1h0pj45/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/datawire/homebrew-blackbird/issues

**Comment by ark3** [comment]
I'm having trouble reproducing this issue. I tried a fresh installation of Homebrew on my 10.13.2 Mac and did not see this crash. Are you using Homebrew's Python3?

**Comment by reinodenoia** [comment]
Thats it! I ad python2 installed. I installed python3 and it worked correctly.

Thank you.

**Comment by ark3** [comment]
I'm glad to hear you got things working.
