### ISSUE TITLE
Warning: Calling <<-EOS.undent is deprecated!

### ISSUE THREAD

**Issue by avinassh** [datawire/homebrew-blackbird#4]
I was installing telepresence and got following warning:

```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:25:in `caveats'
Please report this to the datawire/blackbird tap!
```

https://github.com/datawire/homebrew-blackbird/blob/515edfe9a36844251ac209f04b22aae64b865139/Formula/telepresence.rb#L22

**Comment by ark3** [comment]
Note to self: see http://www.rubydoc.info/github/Homebrew/brew/Formula%3Acaveats for an example.

**Comment by ark3** [comment]
This will be fixed in the next Telepresence release.
